<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="11.9.1" />
		<PackageReference Include="MailKit" Version="4.6.0" />
		<PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" Version="2.2.4" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="8.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="8.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.oAuth" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIDConnect" Version="8.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Twitter" Version="8.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.6" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.2" />
		<PackageReference Include="MimeKit" Version="4.6.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="8.0.2" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Filters\" />
		<Folder Include="Middlewares\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OnDemandTutor.BusinessLogic\OnDemandTutor.BusinessLogic.csproj" />
		<ProjectReference Include="..\OnDemandTutor.Helper\OnDemandTutor.Helper.csproj" />
	</ItemGroup>

</Project>
