// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnDemandTutor.Models;

#nullable disable

namespace OnDemandTutor.Models.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240612100017_Add_FireBase_Id")]
    partial class Add_FireBase_Id
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnDemandTutor.Models.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfStudent")
                        .HasColumnType("int");

                    b.Property<int?>("PriceRatio")
                        .HasColumnType("int");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("money");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("TeachAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.Property<double?>("TutorRating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.ConsultationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConsultationRequests");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("TutorId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Medium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<string>("RefImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualEndtime")
                        .HasColumnType("datetime");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ReferenceId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.TutorDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DegreeImgID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DegreeImgID");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorDegrees");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.TutorTeachTimeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DayOfWeek")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorTeachTimeSchedules");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.TutorVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorVideos");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AvatarImageId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("money");

                    b.Property<int?>("DegreeImageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FireBaseid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdCardImageID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("ScheduleDesciption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DegreeImageId");

                    b.HasIndex("IdCardImageID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SlotTransaction", b =>
                {
                    b.Property<int>("SlotTransactionNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionNavigationId")
                        .HasColumnType("int");

                    b.HasKey("SlotTransactionNavigationId", "TransactionNavigationId");

                    b.HasIndex("TransactionNavigationId");

                    b.ToTable("SlotTransaction");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Blog", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.User", "CreateByNavigation")
                        .WithMany("BlogCreateByNavigations")
                        .HasForeignKey("CreateBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnDemandTutor.Models.Models.User", "UpdateByNavigation")
                        .WithMany("BlogUpdateByNavigations")
                        .HasForeignKey("UpdateBy");

                    b.Navigation("CreateByNavigation");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Class", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.User", "Student")
                        .WithMany("ClassStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnDemandTutor.Models.Models.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnDemandTutor.Models.Models.User", "Tutor")
                        .WithMany("ClassTutors")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.FAQ", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.User", "CreateByNavigation")
                        .WithMany("FAQs")
                        .HasForeignKey("CreateBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByNavigation");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Invitation", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.Class", "Class")
                        .WithMany("Invitations")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnDemandTutor.Models.Models.User", "Tutor")
                        .WithMany("Invitations")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Notification", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.User", "Receiver")
                        .WithMany("Notifications")
                        .HasForeignKey("ReceiverId");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Slot", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.Class", "Class")
                        .WithMany("Slots")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Transaction", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.User", "CreatedByNavigation")
                        .WithMany("TransactionCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnDemandTutor.Models.Models.User", "ReferenceNavigation")
                        .WithMany("TransactionReferences")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ReferenceNavigation");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.TutorDegree", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.Medium", "DegreeImg")
                        .WithMany("TutorDegrees")
                        .HasForeignKey("DegreeImgID");

                    b.HasOne("OnDemandTutor.Models.Models.User", "Tutor")
                        .WithMany("TutorDegrees")
                        .HasForeignKey("TutorId");

                    b.Navigation("DegreeImg");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.TutorTeachTimeSchedule", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.User", "Tutor")
                        .WithMany("TutorTeachTimeSchedules")
                        .HasForeignKey("TutorId");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.TutorVideo", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.User", "Tutor")
                        .WithMany("TutorVideos")
                        .HasForeignKey("TutorId");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.User", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.Medium", "DegreeImage")
                        .WithMany("UserDegreeImages")
                        .HasForeignKey("DegreeImageId");

                    b.HasOne("OnDemandTutor.Models.Models.Medium", "IdCardImage")
                        .WithMany("UserIdCardImages")
                        .HasForeignKey("IdCardImageID");

                    b.Navigation("DegreeImage");

                    b.Navigation("IdCardImage");
                });

            modelBuilder.Entity("SlotTransaction", b =>
                {
                    b.HasOne("OnDemandTutor.Models.Models.Transaction", null)
                        .WithMany()
                        .HasForeignKey("SlotTransactionNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnDemandTutor.Models.Models.Slot", null)
                        .WithMany()
                        .HasForeignKey("TransactionNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Class", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Medium", b =>
                {
                    b.Navigation("TutorDegrees");

                    b.Navigation("UserDegreeImages");

                    b.Navigation("UserIdCardImages");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.Subject", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("OnDemandTutor.Models.Models.User", b =>
                {
                    b.Navigation("BlogCreateByNavigations");

                    b.Navigation("BlogUpdateByNavigations");

                    b.Navigation("ClassStudents");

                    b.Navigation("ClassTutors");

                    b.Navigation("FAQs");

                    b.Navigation("Invitations");

                    b.Navigation("Notifications");

                    b.Navigation("TransactionCreatedByNavigations");

                    b.Navigation("TransactionReferences");

                    b.Navigation("TutorDegrees");

                    b.Navigation("TutorTeachTimeSchedules");

                    b.Navigation("TutorVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
