// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnDemandTutor.DataAccess.Models;

public partial class Blog
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int CreateBy { get; set; }

    public DateTime CreateAt { get; set; }

    public int? UpdateBy { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual User CreateByNavigation { get; set; }

    public virtual User UpdateByNavigation { get; set; }
}