// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnDemandTutor.DataAccess.Models;

public partial class ClassRequest
{
    public int Id { get; set; }

    public int ClassId { get; set; }

    public int TutorId { get; set; }

    public int? ApproverId { get; set; }

    public DateTime RequestDate { get; set; }

    public int Status { get; set; }

    public virtual Class Class { get; set; }

    public virtual User Tutor { get; set; }
}