// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnDemandTutor.DataAccess.Models;

public partial class Class
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int StudentId { get; set; }

    public int? TeacherId { get; set; }

    public int? NumberOfStudent { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? SubjectId { get; set; }

    public string Address { get; set; }
}