// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnDemandTutor.DataAccess.Models;

public partial class ConsultationRequest
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public DateTime RequestDate { get; set; }

    public int Status { get; set; }
}