// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnDemandTutor.DataAccess.Models;

public partial class Faq
{
    public int Id { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public int CreateBy { get; set; }

    public DateTime CreateAt { get; set; }

    public virtual User CreateByNavigation { get; set; }
}