// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnDemandTutor.DataAccess.Models;

public partial class Lesson
{
    public int Id { get; set; }

    public int ClassId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int PaymentStatus { get; set; }

    public DateTime Date { get; set; }

    public virtual Class Class { get; set; }
}