// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnDemandTutor.DataAccess.Models;

public partial class Medium
{
    public int Id { get; set; }

    public string Url { get; set; }

    public DateTime CreateAt { get; set; }

    public virtual ICollection<User> UserDegreeImages { get; set; } = new List<User>();

    public virtual ICollection<User> UserIdCardImages { get; set; } = new List<User>();
}