// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnDemandTutor.DataAccess.Models;

public partial class Notification
{
    public int Id { get; set; }

    public string Content { get; set; }

    public int? ReceiverId { get; set; }

    public string RefUrl { get; set; }

    public string RefImageUrl { get; set; }

    public int ViewStatus { get; set; }

    public virtual User Receiver { get; set; }
}