// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnDemandTutor.DataAccess.Models;

public partial class Subject
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string SubjectType { get; set; }

    public int? CreateBy { get; set; }

    public DateTime? CreateAt { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();
}