// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnDemandTutor.DataAccess.Models;

public partial class TutorVideo
{
    public int Id { get; set; }

    public int? TutorId { get; set; }

    public string VideoUrl { get; set; }

    public string Description { get; set; }

    public virtual User Tutor { get; set; }
}