// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnDemandTutor.DataAccess.Models;

public partial class User
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Avatar { get; set; }

    public int? Status { get; set; }

    public DateTime? Dob { get; set; }

    public string Password { get; set; }

    public int? Role { get; set; }

    public bool? RecordStatus { get; set; }
}