FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION = Release
WORKDIR /src
COPY ["OnDemandTutor.API/OnDemandTutor.API.csproj", "OnDemandTutor.API/"]
COPY ["OnDemandTutor.API/OnDemandTutor.BusinessLogic.csproj", "OnDemandTutor.BusinessLogic/"]
COPY ["OnDemandTutor.API/OnDemandTutor.DataAccess.csproj", "OnDemandTutor.DataAccess/"]
COPY ["OnDemandTutor.API/OnDemandTutor.Helper.csproj", "OnDemandTutor.Helper/"]
COPY ["OnDemandTutor.API/OnDemandTutor.Models.csproj", "OnDemandTutor.Models/"]
COPY ["OnDemandTutor.API/OnDemandTutor.SchedulerJobs.csproj", "OnDemandTutor.SchedulerJobs/"]

RUN dotnet restore "OnDemandTutor.API/OnDemandTutor.API.csproj"

COPY . .

WORKDIR "src/OnDemandTutor.API"
RUN dotnet build "OnDemandTutor.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build as publish
ARG BUILD_CONFIGURATION = Release
RUN dotnet publish "OnDemandTutor.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish

FROM base AS final 
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "OnDemandTutor.API.dll"]