<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Api.CommonProtos" Version="2.15.0" />
        <PackageReference Include="HtmlAgilityPack" Version="1.11.61" />
        <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.1.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Dtos\Subject\" />
        <Folder Include="Dtos\FAQ\" />
        <Folder Include="Dtos\Notification\" />
        <Folder Include="Dtos\StudentClass\" />
        <Folder Include="Dtos\StudentSlot\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Dtos\Slot\" />
      <None Remove="Dtos\Blog\" />
      <None Remove="Dtos\Subject\" />
      <None Remove="Dtos\Class\" />
      <None Remove="Dtos\ConsultationRequestDtos\" />
      <None Remove="Dtos\EmailTemplate\" />
      <None Remove="Dtos\FAQ\" />
      <None Remove="Dtos\Notification\" />
      <None Remove="Dtos\StudentClass\" />
      <None Remove="Dtos\StudentSlot\" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Mvc.Core">
        <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.6\Microsoft.AspNetCore.Mvc.Core.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
