// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnDemandTutor.DataAccess.Models;

#nullable disable

namespace OnDemandTutor.DataAccess.Migrations
{
    [DbContext(typeof(OnDemandTutorContext))]
    [Migration("20240603010840_Add_Identity_Has_Table")]
    partial class Add_Identity_Has_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("UpdateBy");

                    b.ToTable("Blog", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfStudent")
                        .HasColumnType("int");

                    b.Property<int?>("PriceRatio")
                        .HasColumnType("int");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("money");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("TeachAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.Property<double?>("TutorRating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId");

                    b.ToTable("Class", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.ClassRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("TutorId");

                    b.ToTable("ClassRequest", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.ConsultationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConsultationRequest", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.ToTable("FAQ", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("TutorId");

                    b.ToTable("Invitation", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Medium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Media", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<string>("RefImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Notification", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualEndtime")
                        .HasColumnType("datetime");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Lesson");

                    b.HasIndex("ClassId");

                    b.ToTable("Slot", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subject", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<int?>("SlotId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("SlotId");

                    b.ToTable("Transaction", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.TutorDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DegreeImgID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DegreeImgID");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorDegree", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.TutorTeachTimeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DayOfWeek")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Schedule");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorTeachTimeSchedule", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.TutorVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_TutorVIdeo");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorVideo", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AvatarImageId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("money");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DegreeImageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdCardImageID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<bool?>("RecordStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("ScheduleDesciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.HasIndex("DegreeImageId");

                    b.HasIndex("IdCardImageID");

                    b.ToTable("User", "identity");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Blog", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "CreateByNavigation")
                        .WithMany("BlogCreateByNavigations")
                        .HasForeignKey("CreateBy")
                        .IsRequired()
                        .HasConstraintName("FK_Blog_User");

                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "UpdateByNavigation")
                        .WithMany("BlogUpdateByNavigations")
                        .HasForeignKey("UpdateBy")
                        .HasConstraintName("FK_Blog_User1");

                    b.Navigation("CreateByNavigation");

                    b.Navigation("UpdateByNavigation");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Class", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "Student")
                        .WithMany("ClassStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Class_User1");

                    b.HasOne("OnDemandTutor.DataAccess.Models.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Class_Subject");

                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "Tutor")
                        .WithMany("ClassTutors")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("FK_Class_User");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.ClassRequest", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.Class", "Class")
                        .WithMany("ClassRequests")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassRequest_Class");

                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "Tutor")
                        .WithMany("ClassRequests")
                        .HasForeignKey("TutorId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassRequest_User");

                    b.Navigation("Class");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.FAQ", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "CreateByNavigation")
                        .WithMany("FAQs")
                        .HasForeignKey("CreateBy")
                        .IsRequired()
                        .HasConstraintName("FK_FAQ_User");

                    b.Navigation("CreateByNavigation");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Invitation", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.Class", "Class")
                        .WithMany("Invitations")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Invitation_Class");

                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "Tutor")
                        .WithMany("Invitations")
                        .HasForeignKey("TutorId")
                        .IsRequired()
                        .HasConstraintName("FK_Invitation_User");

                    b.Navigation("Class");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Notification", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "Receiver")
                        .WithMany("Notifications")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK_Notification_User");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Slot", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.Class", "Class")
                        .WithMany("Slots")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Lesson_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Transaction", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "CreatedByNavigation")
                        .WithMany("TransactionCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_User1");

                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "Reference")
                        .WithMany("TransactionReferences")
                        .HasForeignKey("ReferenceId")
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_User");

                    b.HasOne("OnDemandTutor.DataAccess.Models.Slot", "Slot")
                        .WithMany("Transactions")
                        .HasForeignKey("SlotId")
                        .HasConstraintName("FK_Transaction_Slot");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Reference");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.TutorDegree", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.Medium", "DegreeImg")
                        .WithMany("TutorDegrees")
                        .HasForeignKey("DegreeImgID")
                        .HasConstraintName("FK_TutorDegree_Media");

                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "Tutor")
                        .WithMany("TutorDegrees")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("FK_TutorDegree_User");

                    b.Navigation("DegreeImg");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.TutorTeachTimeSchedule", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "Tutor")
                        .WithMany("TutorTeachTimeSchedules")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("FK_TutorFreeTimeSchedule_User");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.TutorVideo", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.User", "Tutor")
                        .WithMany("TutorVideos")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("FK_TutorVIdeo_User");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.User", b =>
                {
                    b.HasOne("OnDemandTutor.DataAccess.Models.Medium", "DegreeImage")
                        .WithMany("UserDegreeImages")
                        .HasForeignKey("DegreeImageId")
                        .HasConstraintName("FK_User_Media1");

                    b.HasOne("OnDemandTutor.DataAccess.Models.Medium", "IdCardImage")
                        .WithMany("UserIdCardImages")
                        .HasForeignKey("IdCardImageID")
                        .HasConstraintName("FK_User_Media");

                    b.Navigation("DegreeImage");

                    b.Navigation("IdCardImage");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Class", b =>
                {
                    b.Navigation("ClassRequests");

                    b.Navigation("Invitations");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Medium", b =>
                {
                    b.Navigation("TutorDegrees");

                    b.Navigation("UserDegreeImages");

                    b.Navigation("UserIdCardImages");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Slot", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.Subject", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("OnDemandTutor.DataAccess.Models.User", b =>
                {
                    b.Navigation("BlogCreateByNavigations");

                    b.Navigation("BlogUpdateByNavigations");

                    b.Navigation("ClassRequests");

                    b.Navigation("ClassStudents");

                    b.Navigation("ClassTutors");

                    b.Navigation("FAQs");

                    b.Navigation("Invitations");

                    b.Navigation("Notifications");

                    b.Navigation("TransactionCreatedByNavigations");

                    b.Navigation("TransactionReferences");

                    b.Navigation("TutorDegrees");

                    b.Navigation("TutorTeachTimeSchedules");

                    b.Navigation("TutorVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
